# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - echo "hello"
    silent: true

  build-server:
    dir: server
    cmds: 
      - cargo build --release
  
  run-server:
    dir: server
    env:
      RUST_LOG: trace
      DG_BINDADDRESS: 127.0.0.1:8080
      DG_ALLOWEDORIGINS: "*"
    cmds:
      - cargo run
  
  run:
    cmds:
      - task: run-server
        
  deps-web:
    dir: webclient
    sources:
      - "package.json"
      - "yarn.lock"
    cmds:
      - yarn
  
  run-web:
    dir: webclient
    deps:
      - deps-web
    cmds:
      - yarn start