name: Heroku Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
    paths-ignore:
      - "**.md"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build, Push and Deploy to Heroku
        id: heroku
        uses: mtsmachado8/heroku-deploy@v2.0.3
        with:
          email: ${{ secrets.HEROKU_EMAIL }} 
          api_key: ${{ secrets.HEROKU_API_KEY }}
          app_name: duesgoerd
          dockerfile_path: '' 
          options: ''